### ISSUE TITLE
Generated smithy-rs client using only smithy-cli and smithy-build file

### ISSUE THREAD

**Issue by NukaCody** [smithy-lang/smithy-rs#3181]
It looks like params is null [here](https://github.com/smithy-lang/smithy-rs/blob/63ce3f951ea9631d47edaf4d3005be1993bfaa43/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/generators/EndpointParamsInterceptorGenerator.kt#L108) maybe?

I added these lines write below it

```kotlin
    private fun paramSetters(operationShape: OperationShape, params: Parameters) = writable {
        println("params: $params, type: ${params?.javaClass?.canonicalName}")
        println(Parameters::class.java.getClassLoader())
```

and got this when running `smithy build`:

```bash
params: , type: software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters
java.net.URLClassLoader@27ddd392
```

Params prints nothing even though Parameters has a toString() impl. Then a cast error is thrown. It's as if Java knows that Parameters exist, but doesn't know anything about it's implementation. Even weirder is that Parameters defaults to an empty list [here](https://github.com/smithy-lang/smithy-rs/blob/12fa4d3963eaee9105339971ff1e6e1e185c95fd/codegen-client/src/main/kotlin/software/amazon/smithy/rust/codegen/client/smithy/endpoint/EndpointTypesGenerator.kt#L29) which makes me think that I'm somehow not including `Parameters` when I do a `publishToMavenLocal`? 

```bash
Projection rs-sdk failed: java.lang.ClassCastException: class software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters cannot be cast to class java.lang.Iterable (software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters is in unnamed module of loader java.net.URLClassLoader @27ddd392; java.lang.Iterable is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters cannot be cast to class java.lang.Iterable (software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters is in unnamed module of loader java.net.URLClassLoader @27ddd392; java.lang.Iterable is in module java.base of loader 'bootstrap')
        at software.amazon.smithy.rust.codegen.client.smithy.endpoint.generators.EndpointParamsInterceptorGenerator$paramSetters$1.invoke(EndpointParamsInterceptorGenerator.kt:114)
        at software.amazon.smithy.rust.codegen.client.smithy.endpoint.generators.EndpointParamsInterceptorGenerator$paramSetters$1.invoke(EndpointParamsInterceptorGenerator.kt:108)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriter$RustSymbolFormatter.apply(RustWriter.kt:825)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriter$RustSymbolFormatter.apply(RustWriter.kt:797)
        at software.amazon.smithy.utils.AbstractCodeWriter.applyFormatter(AbstractCodeWriter.java:1989)
        at software.amazon.smithy.utils.CodeFormatter$Operation.lambda$formatted$1(CodeFormatter.java:108)
        at software.amazon.smithy.utils.CodeFormatter$BlockOperation$Unconditional.apply(CodeFormatter.java:228)
        at software.amazon.smithy.utils.CodeFormatter.run(CodeFormatter.java:41)
        at software.amazon.smithy.utils.AbstractCodeWriter.format(AbstractCodeWriter.java:1673)
        at software.amazon.smithy.utils.AbstractCodeWriter.write(AbstractCodeWriter.java:1732)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriter.write(RustWriter.kt:544)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriterKt$rustTemplate$1.invoke(RustWriter.kt:249)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriterKt$rustTemplate$1.invoke(RustWriter.kt:248)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriterKt.withTemplate(RustWriter.kt:112)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriterKt.withTemplate$default(RustWriter.kt:98)
        at software.amazon.smithy.rust.codegen.core.rustlang.RustWriterKt.rustTemplate(RustWriter.kt:248)
        at software.amazon.smithy.rust.codegen.client.smithy.endpoint.generators.EndpointParamsInterceptorGenerator.render(EndpointParamsInterceptorGenerator.kt:72)
        at software.amazon.smithy.rust.codegen.client.smithy.generators.OperationGenerator.renderOperationStruct(OperationGenerator.kt:205)
        at software.amazon.smithy.rust.codegen.client.smithy.generators.OperationGenerator.renderOperation(OperationGenerator.kt:56)
        at software.amazon.smithy.rust.codegen.client.smithy.ClientCodegenVisitor$operationShape$1.invoke(ClientCodegenVisitor.kt:308)
        at software.amazon.smithy.rust.codegen.client.smithy.ClientCodegenVisitor$operationShape$1.invoke(ClientCodegenVisitor.kt:306)
        at software.amazon.smithy.rust.codegen.core.smithy.RustCrate.withModule$lambda$6(CodegenDelegator.kt:199)
        at software.amazon.smithy.codegen.core.WriterDelegator.useFileWriter(WriterDelegator.java:175)
        at software.amazon.smithy.rust.codegen.core.smithy.RustCrate.withModule(CodegenDelegator.kt:198)
        at software.amazon.smithy.rust.codegen.core.smithy.RustCrate.useShapeWriter(CodegenDelegator.kt:98)
        at software.amazon.smithy.rust.codegen.client.smithy.ClientCodegenVisitor.operationShape(ClientCodegenVisitor.kt:306)
        at software.amazon.smithy.rust.codegen.client.smithy.ClientCodegenVisitor.operationShape(ClientCodegenVisitor.kt:60)
        at software.amazon.smithy.model.shapes.OperationShape.accept(OperationShape.java:87)
        at software.amazon.smithy.rust.codegen.client.smithy.ClientCodegenVisitor.execute(ClientCodegenVisitor.kt:158)
        at software.amazon.smithy.rust.codegen.client.smithy.RustClientCodegenPlugin.executeWithDecorator(RustClientCodegenPlugin.kt:75)
        at software.amazon.smithy.rust.codegen.client.testutil.ClientDecoratableBuildPlugin.execute(ClientCodegenIntegrationTest.kt:54)
        at software.amazon.smithy.build.SmithyBuildImpl.applyPlugin(SmithyBuildImpl.java:432)
        at software.amazon.smithy.build.SmithyBuildImpl.applyProjection(SmithyBuildImpl.java:364)
        at software.amazon.smithy.build.SmithyBuildImpl.executeSerialProjection(SmithyBuildImpl.java:281)
        at software.amazon.smithy.build.SmithyBuildImpl.lambda$applyAllProjections$4(SmithyBuildImpl.java:201)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Steps taken:
1. Fresh pull and checkout smithy-rs-release-0.57.x
2. `./gradlew publishToMavenLocal`
3. smithy mentioned below
4. smithy build

Smithy-CLI version: 1.41.0

Build file sample

```json
 "rs-sdk": {
      "plugins": {
        "rust-client-codegen": {
          "service": "aws.is#IdentityService",
          "module": "is_sdk",
          "moduleDescription": "Identity Service SDK",
          "moduleVersion": "0.0.1",
          "moduleAuthors": [
            "IS Team"
          ],
          "runtimeConfig": {
            "version": "DEFAULT"
          }
        }
      }
    }
    
    ....
  "maven": {
    "dependencies": [
      "software.amazon.smithy:smithy-cli:1.41.0",
      "software.amazon.smithy:smithy-model:1.41.0",
      "software.amazon.smithy:smithy-openapi:1.41.0",
      "software.amazon.smithy:smithy-aws-traits:1.41.0",
      "software.amazon.smithy:smithy-validation-model:1.41.0",
      "software.amazon.smithy:smithy-aws-apigateway-openapi:1.41.0",
      "software.amazon.smithy.typescript:smithy-typescript-codegen:0.17.1",
      "software.amazon.smithy.typescript:smithy-typescript-codegen:0.17.1",
      "software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.17.1",
      "software.amazon.smithy.rust.codegen.server.smithy:codegen-server:0.1.0",
      "software.amazon.smithy.rust.codegen:codegen-client:0.1.0"
    ]
  }
```

Edit:

I'm in too deep, pull me out boss....

After listing all methods and explicitly calling iterator()

```kotlin
    private fun paramSetters(operationShape: OperationShape, params: Parameters) = writable {
        println("params: $params, type: ${params?.javaClass?.canonicalName}")
        println(Parameters::class.java.getClassLoader())
        Parameters::class.java.declaredMethods.forEach { method ->
            println(method)
        }

        println(params.iterator())
```

I get a MethodNotFound error

```bash
Projection rs-sdk failed: java.lang.NoSuchMethodError: 'java.util.Iterator software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters.iterator()'
java.lang.NoSuchMethodError: 'java.util.Iterator software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters.iterator()'
        at software.amazon.smithy.rust.codegen.client.smithy.endpoint.generators.EndpointParamsInterceptorGenerator$paramSetters$1.invoke(EndpointParamsInterceptorGenerator.kt:115)
```

IntelliJ recognizes as a valid method and it's definitely there which makes me believe this is some weird build issue. Maybe I need to do more than just `publishToMavenLocal` for the client. (works fine for server-side)

**Comment by codypenta** [comment]
I'm in way too deep...pull me out boss...it looks like Parameter does not implement iterator, explicitly calling `.iterator()` gives this error.

```kotlin
    private fun paramSetters(operationShape: OperationShape, params: Parameters) = writable {
        println("params: $params, type: ${params?.javaClass?.canonicalName}")
        println(Parameters::class.java.getClassLoader())
        Parameters::class.java.declaredMethods.forEach { method ->
            println(method)
        }

        println(params.iterator()) // Throws
```

```bash
Projection rs-sdk failed: java.lang.NoSuchMethodError: 'java.util.Iterator software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters.iterator()'
java.lang.NoSuchMethodError: 'java.util.Iterator software.amazon.smithy.rulesengine.language.syntax.parameters.Parameters.iterator()'
        at software.amazon.smithy.rust.codegen.client.smithy.endpoint.generators.EndpointParamsInterceptorGenerator$paramSetters$1.invoke(EndpointParamsInterceptorGenerator.kt:115)
```

Intellij recognizes it as a valid method call, which really makes me think this is something to do with building/dependency management

**Comment by NukaCody** [comment]
Found it, Add

>       "software.amazon.smithy:smithy-rules-engine:1.41.0",

to your smithy-build file.
